version: "3.9"

networks:
  default:
    name: ${COMPOSE_PROJECT_NAME}

services:
  app:
    image: node:18.15.0
    user: node
    working_dir: /home/node/app
    ports:
      - 80:3000
    volumes:
      - ./:/home/node/app
    extra_hosts: # For Linux
      - host.docker.internal:host-gateway
    tty: true
    expose:
      - 3000
    command: "npm run dev"
